# Generated by Django 3.2.9 on 2021-11-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcollection',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='idcollection',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
