# Generated by Django 3.2.9 on 2021-11-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20211126_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcollection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(max_length=200)),
                ('comment_body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('founddocument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.idcollection')),
            ],
        ),
    ]
