# Generated by Django 3.2.9 on 2021-11-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20211127_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idcollection',
            old_name='worker',
            new_name='user',
        ),
        migrations.AddField(
            model_name='idcollection',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
