# Generated by Django 3.2.9 on 2021-11-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcollection',
            name='name',
            field=models.CharField(default='names', max_length=225),
        ),
    ]
