# Generated by Django 3.2.9 on 2021-12-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20211130_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcollection',
            name='image',
            field=models.ImageField(blank=True, default='image/download.png', null=True, upload_to='image'),
        ),
    ]
