# Generated by Django 3.2.9 on 2021-12-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_idcollection_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
