# Generated by Django 3.2.9 on 2021-12-01 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_on',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
