# Generated by Django 3.2.9 on 2021-12-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
