# Generated by Django 3.2.9 on 2021-12-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('message', models.TextField()),
                ('created_on', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Ordering',
        ),
    ]
